# permissions for end users to view httpgzips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpgzip-viewer-role
rules:
- apiGroups:
  - apps.vadasambar.com
  resources:
  - httpgzips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.vadasambar.com
  resources:
  - httpgzips/status
  verbs:
  - get
