# permissions for end users to edit httpgzips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpgzip-editor-role
rules:
- apiGroups:
  - apps.vadasambar.com
  resources:
  - httpgzips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.vadasambar.com
  resources:
  - httpgzips/status
  verbs:
  - get
